//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Rwa.Mvc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkHoursEntities : DbContext
    {
        public WorkHoursEntities()
            : base("name=WorkHoursEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Djelatnik> Djelatniks { get; set; }
        public virtual DbSet<Klijent> Klijents { get; set; }
        public virtual DbSet<Projekt> Projekts { get; set; }
        public virtual DbSet<ProjektDjelatnik> ProjektDjelatniks { get; set; }
        public virtual DbSet<Tim> Tims { get; set; }
        public virtual DbSet<TipDjelatnika> TipDjelatnikas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<RadniSati> RadniSatis { get; set; }
    }
}
