//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Rwa.Mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjektDjelatnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjektDjelatnik()
        {
            this.RadniSatis = new HashSet<RadniSati>();
        }
    
        public short IDProjektDjelatnik { get; set; }
        public short ProjektID { get; set; }
        public short DjelatnikID { get; set; }
    
        public virtual Djelatnik Djelatnik { get; set; }
        public virtual Projekt Projekt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RadniSati> RadniSatis { get; set; }
    }
}
