//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Rwa.Mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadniSati
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RadniSati()
        {
            this.ProjektDjelatniks = new HashSet<ProjektDjelatnik>();
        }
    
        public byte IDRadniSati { get; set; }
        public System.DateTime PocetakTrajanja { get; set; }
        public System.DateTime KrajTrajanja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjektDjelatnik> ProjektDjelatniks { get; set; }
    }
}
