//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Rwa.Mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadniSati
    {
        public byte IDRadniSati { get; set; }
        public System.DateTime PocetakTrajanja { get; set; }
        public System.DateTime KrajTrajanja { get; set; }
        public Nullable<short> ProjektDjelatnikID { get; set; }
    
        public virtual ProjektDjelatnik ProjektDjelatnik { get; set; }
    }
}
